version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.75'
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.production
    depends_on:
      - backend
